### ISSUE TITLE
game.data file doesn't work

### ISSUE THREAD

**Issue by HaysonWong** [HTCheater/SKDEditor#2]
After editing the game.data file, the data in soul knight doesn't get changed at all. Every other file works normally and can be edited, but editing the game.data file just doesn't do anything at all

**Comment by HaysonWong** [comment]
Ok I suddenly felt like I should elaborate more about the fact that I know that the file in shared pref still works, but why game.data if it doesn't even work in the first place?

**Comment by HTCheater** [comment]
Can you give me logcat logs? Did you close the game before editing?

**Comment by HTCheater** [comment]
Also it may not be an issue of SKDEditor at all because game.data is a junk file, there are a lot of useless objects like skinLock. Skins are supposed to be edited in player prefs and changes in game.data are ignored. But for some reason skins are saved in both, that's just how the game works. 😔
