### ISSUE TITLE
SKDEditor stays black

### ISSUE THREAD

**Issue by Leo1342v2** [HTCheater/SKDEditor#5]
Well, I just want to clarify that I am using the Google translator in case you find inconsistencies in the text that you will see below.

I have a Redmi K40 Gaming and I have Magisk and LSPosed and when I open SKDEditor the screen stays black and absolutely nothing happens, I already tried it in VMOS Pro and despite the fact that the soul knight crashes due to the game's cheat detector yes SKDEditor was working, so here I attach a picture of the problem.
(https://github.com/HTCheater/SKDEditor/assets/139981649/5ea20afe-8fe3-4034-bc36-ba79b5befbd7)

**Comment by HTCheater** [comment]
Weird
Won't fix soon because already working on update
