### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Pogzhsd2** [HTCheater/SKDEditor#6]
**Describe the bug**
Soul Knight isn't installed?

**Checklist**
- [V] I have root permissions to use SKDE.
- [X] I have attached logcat.
- [X] I have provided steps to reproduce the bug.
- [X] I have provided screenshots (or videorecording of the isuue).
- [Android 12 (VMOS Emulator)] I have provided Android version of the device it is running on.

**Comment by Pogzhsd2** [comment]
Checkmark logo = X

**Comment by HTCheater** [comment]
I don't think you attached the logs, I created the checklist for a reason. Putting "toybox" in the custom toybox command should resolve the issue
