### ISSUE TITLE
App keeps crashing

### ISSUE THREAD

**Issue by xMoun** [HTCheater/SKDEditor#7]
i installed the apk file and installed it. The app is refusing to run

**Comment by HTCheater** [comment]
You didn't provide any specific infornmation. Am I supposed to guess what's wrong? Anyway the app is being rewritten, so any issues with SKDE 3 isn't going to be fixed

**Comment by xMoun** [comment]
i have no idea what was going on. not an expert in these types of things.
anyways i don't need it anymore.

**Comment by RTAkland** [comment]
> i installed the apk file and installed it. The app is refusing to run

are you root?
